---
- name: Initialize and gather required facts
  hosts: localhost
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
      tags: always
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"
      tags: always

- name: Check VRF Ping TFTP Server
  hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
    tftp_server: "10.70.128.32"
  tasks:
    - name: Ping TFTP server via default VRF
      aoscx_command:
        commands: "ping {{ tftp_server }} repetitions 2 vrf default"
      register: ping_default
      ignore_errors: yes
      changed_when: false

    - name: Ping TFTP server via mgmt VRF
      aoscx_command:
        commands: "ping {{ tftp_server }} repetitions 2 vrf mgmt"
      register: ping_mgmt
      ignore_errors: yes
      changed_when: false
      when: "'ping4: connect: Network is unreachable' not in ping_default.stderr|default('')"

    - name: Determine which VRF to use
      set_fact:
        target_vrf: >-
          {% if ping_default is success and 'bytes from' in ping_default.stdout[0] %}
          default
          {% elif ping_mgmt is success and 'bytes from' in ping_mgmt.stdout[0] %}
          mgmt
          {% else %}
          default
          {% endif %}

- name: Backup running config
  hosts: BEL-01SWI0103
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create backup filename
      set_fact:
        backup_filename: "{{ inventory_hostname }}_{{ hostvars.localhost.DTG }}_runconfig.cli"
    - name: Backup running config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/running_config/{{ backup_filename }}'
        config_type: 'cli'
        vrf: "{{ target_vrf | trim }}"
      register: backup_result
      retries: 3
      delay: 10
      until: backup_result is succeeded