---
- name: Copy Running Config to NAS storage with dtm
  hosts: localhost
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

- name: Check HTTPS Server VRF Configuration
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check for HTTPS server configuration
      aoscx_command:
        commands: "show running-config | include https-server"
      register: https_config
      changed_when: false
    - name: Determine VRF configuration
      set_fact:
        target_vrf: >-
          {% if 'https-server vrf mgmt' in https_config.stdout[0] %}
          mgmt
          {% else %}
          default
          {% endif %}
          
- name: Backup running config
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Backup running config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/running_config/{{ inventory_hostname }}_{{hostvars.localhost.DTG}}_runconfig.cli'
        config_type: 'cli'
        vrf: "{{target_vrf | trim }}"