---
- name: Initialize and gather required facts
  hosts: localhost
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

- name: Check VRF Ping TFTP Server
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
  tasks:
    - name: Ping TFTP server via default VRF
      aoscx_command:
        commands: "ping {{ hostvars['localhost']['tftp_server'] }} repetitions {{ hostvars['localhost']['ping_repetitions'] }} vrf default"
      register: ping_default
      ignore_errors: yes
      changed_when: false

    - name: Ping TFTP server via mgmt VRF
      aoscx_command:
        commands: "ping {{ hostvars['localhost']['tftp_server'] }} repetitions {{ hostvars['localhost']['ping_repetitions'] }} vrf mgmt"
      register: ping_mgmt
      ignore_errors: yes
      changed_when: false
      when: >-
        ping_default is failed or 
        ('100% packet loss' in ping_default.stdout[0]|default('') or
         'Network is unreachable' in ping_default.stdout[0]|default('') or
         'ping4: connect' in ping_default.stderr|default(''))

    - name: Determine which VRF to use
      set_fact:
        target_vrf: >-
          {% if ping_default is success and 'bytes from' in ping_default.stdout[0]|default('') %}
            default
          {% elif ping_mgmt is success and 'bytes from' in ping_mgmt.stdout[0]|default('') %}
            mgmt
          {% else %}
            default
          {% endif %}

- name: Backup running config
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
  tasks:
    - name: Create backup filename
      set_fact:
        backup_filename: "{{ inventory_hostname }}_{{ hostvars['localhost']['DTG'] }}_runconfig.cli"

    - name: Backup running config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://{{ hostvars["localhost"]["tftp_server"] }}/{{ hostvars["localhost"]["tftp_directory"] }}/{{ backup_filename }}'
        config_type: 'cli'
        vrf: "{{ target_vrf | trim }}"
      register: backup_result
      retries: 3
      delay: 10
      until: backup_result is succeeded
      ignore_errors: yes

    - name: Register backup status
      set_fact:
        host_backup_status: 
          host: "{{ inventory_hostname }}"
          result: "{{ backup_result is succeeded }}"
      delegate_to: localhost
      run_once: true

- name: Prepare notification output
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Compile backup results
      set_fact:
        notification_backup_results: |
          Backup Results:
          {% for host in ansible_play_hosts_all %}
          - {{ host }}: {% if hostvars[host].host_backup_status.result %}✅ SUCCESS{% else %}❌ FAILED{% endif %}
          {% endfor %}
      run_once: true

    - name: Debug output (optional)
      debug:
        var: notification_backup_results   