---
- name: Check HTTPS Server VRF Configuration
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check for HTTPS server configuration
      aoscx_command:
        commands: "show running-config | include https-server"
      register: https_config
      changed_when: false
    - name: Determine VRF configuration
      set_fact:
        https_vrf: >-
          {% if 'https-server vrf mgmt' in https_config.stdout[0] %}
          mgmt
          {% else %}
          default
          {% endif %}
    - name: Display result
      debug:
        msg: "HTTPS server is configured for VRF {{ https_vrf }}"