---
- name: Check HTTPS Server VRF Configuration
  hosts: aruba_switches
  gather_facts: false
  collections:
    - arubanetworks.aoscx

  tasks:
    - name: Get running configuration
      arubanetworks.aoscx.show_config:
        config: "running-config"
        output: "text"
      register: running_config

    - name: Check for HTTPS server in mgmt VRF
      set_fact:
        https_vrf: "mgmt"
      when: '"https-server vrf mgmt" in running_config.stdout'

    - name: Set default VRF if mgmt not found
      set_fact:
        https_vrf: "default"
      when: '"https-server vrf mgmt" not in running_config.stdout'

    - name: Display HTTPS VRF configuration
      debug:
        msg: "HTTPS server is configured for VRF {{ https_vrf }}"