---
- name: Copy Running Config to NAS storage with dtm
  hosts: localhost
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

- hosts: all
  gather_facts: false
  collections:
      - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
  tasks:
    - name: Set VRF based on platforms value
      set_fact:
        target_vrf: >-
          {% if platforms is defined and 'aoscx_l2' in platforms %}
          default
          {% elif platforms is defined and 'aoscx' in platforms %}
          mgmt
          {% else %}
          default
          {% endif %}
    - name: Show platforms value and VRF selection
      debug:
        msg: "Host {{inventory_hostname}} - Platforms: {{ platforms | default('undefined') }}, Using VRF: {{target_vrf}}"
    - name: Backup running config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/running_config/{{ inventory_hostname }}_{{hostvars.localhost.DTG}}_runconfig.cli'
        config_type: 'cli'
        vrf: '{{target_vrf}}'