---
- name: Copy Running Config to NAS storage with dtm
  hosts: localhost
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"
- hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    tftp_server: "10.70.128.32"
    ansible_command_timeout: 60
  tasks:
    - name: Ping TFTP server via default VRF
      aoscx_command:
        commands: "ping {{ tftp_server }} vrf default repetitions 4"
      register: ping_default
      ignore_errors: yes
      changed_when: false
    - name: Ping TFTP server via mgmt VRF
      aoscx_command:
        commands: "ping {{ tftp_server }} vrf mgmt repetitions 4"
      register: ping_mgmt
      ignore_errors: yes
      changed_when: false
    - name: Determine which VRF to use
      set_fact:
        target_vrf: >-
          {% if ping_default is success and 'bytes from' in ping_default.stdout[0] %}
          default
          {% elif ping_mgmt is success and 'bytes from' in ping_mgmt.stdout[0] %}
          mgmt
          {% else %}
          default
          {% endif %}
    - name: Debug selected VRF
      debug:
        msg: "Using VRF: {{ target_vrf }}"
    - name: Show platforms value and VRF selection
      debug:
        msg: "Host {{inventory_hostname}} - Platforms: {{ platforms | default('undefined') }}, Using VRF: {{target_vrf}}"
    - name: Backup running config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://{{ tftp_server }}/running_config/{{ inventory_hostname }}_{{hostvars.localhost.DTG}}_runconfig.cli'
        config_type: 'cli'
        vrf: "{{target_vrf | trim }}"