---
- name: Backup Running Config using Inventory Platforms Variable
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  
  vars:
    tftp_server: "10.70.128.32"
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
  
  tasks:
    # Get timestamp
    - name: Get current date
      run_once: true
      delegate_to: localhost
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
      register: datetime

    - name: Set DTG fact
      set_fact:
        DTG: "{{ datetime.ansible_facts.ansible_date_time.date }}"

    # Determine VRF from platforms list
    - name: Set VRF based on platforms value
      set_fact:
        target_vrf: >-
          {% if platforms is defined and 'aoscx_l2' in platforms %}
          default
          {% elif platforms is defined and 'aoscx' in platforms %}
          mgmt
          {% else %}
          default
          {% endif %}

    # Debug output
    - name: Show platforms value and VRF selection
      debug:
        msg: "Host {{ inventory_hostname }} - Platforms: {{ platforms | default('undefined') }}, Using VRF: {{ target_vrf }}"

    # Execute backup
    - name: Backup running config
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://{{ tftp_server }}/run_config/{{ inventory_hostname }}_{{ DTG }}_runconfig.cli'
        config_type: 'cli'
        vrf: "{{ target_vrf }}"