---
- name: Convert server UTC time to +10 timezone and custom format
  hosts: localhost
  gather_facts: yes
  tasks:

    - name: Ensure required facts are gathered
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Convert UTC time to +10 timezone and format as DD_MM_YYYY_HHMM
      set_fact:
        DTG_local: >-
          {{ ansible_date_time.iso8601
             | community.general.to_datetime
             | community.general.to_tz('+10')
             | strftime('%d_%m_%Y_%H%M') }}

    - name: Show formatted local time
      debug:
        msg: "Local time (+10): {{ DTG_local }}"

- name: Check VRF Ping TFTP Server
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
  tasks:
    - name: Ping TFTP server via default VRF
      aoscx_command:
        commands: "ping {{ tftp_server }} repetitions {{ ping_repetitions }} vrf default"
      register: ping_default
      ignore_errors: yes
      changed_when: false

    - name: Ping TFTP server via mgmt VRF
      aoscx_command:
        commands: "ping {{ tftp_server }} repetitions {{ ping_repetitions }} vrf mgmt"
      register: ping_mgmt
      ignore_errors: yes
      changed_when: false
      when: >-
        ping_default is failed or 
        ('100% packet loss' in ping_default.stdout[0]|default('') or
         'Network is unreachable' in ping_default.stdout[0]|default('') or
         'ping4: connect' in ping_default.stderr|default(''))

    - name: Determine which VRF to use
      set_fact:
        target_vrf: >-
          {% if ping_default is success and 'bytes from' in ping_default.stdout[0]|default('') %}
            default
          {% elif ping_mgmt is success and 'bytes from' in ping_mgmt.stdout[0]|default('') %}
            mgmt
          {% else %}
            default
          {% endif %}

- name: Backup startup config
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
  tasks:
    - name: Create backup filename
      set_fact:
        backup_filename: "{{ inventory_hostname }}_{{ hostvars['localhost']['DTG_local'] }}_startconfig.cli"

    - name: Backup startup config
      aoscx_backup_config:
        config_name: 'startup-config'
        remote_output_file_tftp_path: 'tftp://{{ tftp_server }}/{{ tftp_directory }}/{{ backup_filename }}'
        config_type: 'cli'
        vrf: "{{ target_vrf | trim }}"
      register: backup_result
      retries: 3
      delay: 10
      until: backup_result is succeeded
      ignore_errors: yes
      changed_when: "backup_result is succeeded"

    - name: Register backup result as host fact
      set_fact:
        backup_result: "{{ backup_result }}"

- name: Aggregate backup results
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Collect all backup results into master fact
      set_fact:
        backup_results: "{{ backup_results | default({}) | combine({ item: (hostvars[item] | default({})).get('backup_result', 'No result') }) }}"
      loop: "{{ groups['all'] }}"

- name: Send backup result notification email
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Send email with backup results
      community.general.mail:
        host: smtp.timberlinkaustralia.com.au
        port: 25
        from: awx@timberlinkaustralia.com.au
        to: "{{ email_recipients }}"
        subject: "TL Switch Backup Results - Startup Config"
        body: |

          Job: {{ awx_job_name | default('Unknown Job') }}
          Job ID: {{ tower_job_id | default('N/A') }}
          Job Status: ✅ Completed

          TFTP Server: {{ tftp_server_name | default('Not Set') }}
          TFTP Directory: {{ tftp_directory | default('/default/path') }}
          Date: {{ DTG_local | default('Unknown Date') }}

          ==========================================================

          Bell Bay:
          {% for host, result in backup_results.items() if host.startswith('BEL') %}
            {{ host }}: 
            {% if result is succeeded or (result.failed == False) %}
                ✅ Successful - Attempts: {{ result.attempts | default('N/A') }}
            {% else %}
                ❌ Failed - {{ result | to_nice_json }}
            {% endif %}
          {% else %}
            No Bell Bay switches in backup results
          {% endfor %}
          
          ==========================================================

          Tarpeena:
          {% for host, result in backup_results.items() if host.startswith('TAR') %}
            {{ host }}: 
            {% if result is succeeded or (result.failed == False) %}
                ✅ Successful - Attempts: {{ result.attempts | default('N/A') }}
            {% else %}
                ❌ Failed - {{ result | to_nice_json }}
            {% endif %}
          {% else %}
            No Tarpeena switches in backup results
          {% endfor %}
          
          ==========================================================
          
          Other Sites:
          {% for host, result in backup_results.items() if not host.startswith('BEL') and not host.startswith('TAR') %}
            {{ host }}: 
            {% if result is succeeded or (result.failed == False) %}
                ✅ Successful - Attempts: {{ result.attempts | default('N/A') }}
            {% else %}
                ❌ Failed - {{ result | to_nice_json }}
            {% endif %}
          {% else %}
            No other site switches in backup results
          {% endfor %}
        subtype: plain